# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.0.1
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: check-yaml
    -   id: check-added-large-files
    -   id: check-ast
    -   id: debug-statements

-   repo: https://github.com/psf/black
    rev: 21.11b1
    hooks:
    -   id: black

-   repo: https://github.com/asottile/seed-isort-config
    rev: v2.2.0
    hooks:
    -   id: seed-isort-config

-   repo: https://github.com/pre-commit/mirrors-isort
    rev: v5.9.3
    hooks:
    -   id: isort
        args: ["--profile", "black"]

-   repo: https://github.com/pre-commit/mirrors-mypy
    rev: v0.910-1
    hooks:
    -   id: mypy
        args: [--no-strict-optional, --ignore-missing-imports, --install-types, --non-interactive]

-   repo: https://gitlab.com/pycqa/flake8
    rev: '3.9.2'
    hooks:
    -   id: flake8
